### PR TITLE
Correct the logic to add -1 depth account-group as immediate parent 

### PR DESCRIPTION
**Pull request by namratabhadauriya**
### Description

Correct the logic to add -1 depth account-group as immediate parent  instead of making same depth account group as parent

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
@toddgiguere want to take a look?

**Comment by ocofaigh** [comment]
@namratabhadauriya I see the tests failing with: `Error: DeleteAccountWithContext failed Gateway Timeout` - is there some backend issue?

**Comment by namratabhadauriya** [comment]
@ocofaigh @toddgiguere  I am not sure, on vacation currently, pipeline is passing now can you please review it.

**Review by toddgiguere — APPROVED** [review]

**Comment by toddgiguere** [comment]
@ocofaigh the source looks good, I think I would classify this as a "fix" and not a "feat"? I think it will be a bugfix officially, so a patch version makes more sense?

**Pull request merged**
